apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generateName: create-aws-secret-
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  entrypoint: create-secret
  destination:
    namespace: crossplane-system
    name: in-cluster
  project: appbundle-project-dev
  templates:
    - name: create-secret
      container:
        image: bitnami/kubectl
        command: [kubectl, create, secret, generic, aws-secret, -n, crossplane-system, --dry-run=client, -o, yaml]
        volumeMounts:
          - name: credentials
            mountPath: /credentials
      volumes:
        - name: credentials
          emptyDir: {}

