apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-upbound-aws-provider
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: crossplane-system
    name: in-cluster
  project: appbundle-project-dev
  source:
    chart: upbound-provider-aws
    targetRevision: HEAD
    repoURL: https://charts.upbound.io/stable
    helm:
      parameters:
        - name: provider-aws.version
          value: v0.27.0


