# path/to/helm-charts/upbound-provider-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providers.pkg.crossplane.io
spec:
  group: pkg.crossplane.io
  names:
    kind: Provider
    plural: providers
    singular: provider
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
