apiVersion: v1
kind: List
items:
  - apiVersion: s3.aws.upbound.io/v1beta1
    kind: Bucket
    metadata:
      name: crossplane-bucket-xcdb-variance
      labels:
        docs.crossplane.io/example: provider-aws
    spec:
      forProvider:
        region: us-east-1
      providerConfigRef:
        name: upbound-provider-aws-config
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: VPC
    metadata:
      name: crossplane-vpc-xsample
      labels:
        docs.crossplane.io/example: provider-aws
    spec:
      cidrBlock: 10.0.0.0/16
      forProvider:
        region: us-east-1
      providerConfigRef:
        name: upbound-provider-aws-config