apiVersion: v1
kind: List
items:
  - apiVersion: s3.aws.upbound.io/v1beta1
    kind: Bucket
    metadata:
      name: crossplane-bucket-xcdb-variance
      labels:
        docs.crossplane.io/example: provider-aws
    spec:
      forProvider:
        region: us-east-1
      providerConfigRef:
        name: upbound-provider-aws-config
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: VPC
    metadata:
      name: crossplane-vpc-xsample
      labels:
        docs.crossplane.io/example: provider-aws
    spec:      
      forProvider:
        region: us-east-1
        cidrBlock: 10.0.0.0/16
        tags:
          Name: crossplane-vpc-xsample
      providerConfigRef:
        name: upbound-provider-aws-config
      publishConnectionDetails:
        - key: vpc-id
          valueFrom:
            jsonPath: "{.status.vpcId}"
