apiVersion: v1
kind: List
items:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: s3.buckets.pkg.crossplane.io
  
  - apiVersion: s3.aws.upbound.io/v1beta1
    kind: Bucket
    metadata:
      generateName: crossplane-bucket-
      labels:
        docs.crossplane.io/example: provider-aws
    spec:
      forProvider:
        region: us-east-1
      providerConfigRef:
        name: upbound-provider-aws-config