apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providers.pkg.crossplane.io
spec:
  group: pkg.crossplane.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    kind: Provider
    plural: providers
    singular: provider
    shortNames:
      - p
  additionalPrinterColumns:
    - name: Package
      type: string
      JSONPath: .spec.package
    - name: PackageType
      type: string
      JSONPath: .spec.packageType
    - name: ReclaimPolicy
      type: string
      JSONPath: .spec.reclaimPolicy

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane
  namespace: crossplane-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane:system:controller
rules:
  - apiGroups:
      - pkg.crossplane.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane:system:controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane:system:controller
subjects:
  - kind: ServiceAccount
    name: crossplane
    namespace: crossplane-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  selector:
    matchLabels:
      app: crossplane
  template:
    metadata:
      labels:
        app: crossplane
    spec:
      serviceAccountName: crossplane
      containers:
        - name: crossplane
          image: crossplane/crossplane:latest
          args:
            - "crossplane"
          ports:
            - containerPort: 1337
          volumeMounts:
            - name: extensions
              mountPath: /ext
      volumes:
        - name: extensions
          emptyDir: {}
