apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  source:
    repoURL: https://github.com/rkakarlapudi14/aggr-infra.git
    targetRevision: main
    path: /infra
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
