apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-helm-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  source:
    helm:
      parameters:
        - name: values
          value: |
            {{- include "crossplane.global" . | nindent 2 }}
            {{- include "crossplane.values" . | nindent 2 }}
      chart: crossplane
      repoURL: 'https://charts.crossplane.io/stable'
      targetRevision: ""
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
