apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
      chart: crossplane-stable/crossplane
      version: 1.3.0
  values: |
    # Add your custom values here
    # Example:
    rbac:
      create: true
      serviceAccount:
        create: true
        name: crossplane-serviceaccount
